python3 plan-ddpg.py --evalout pendulum/01_evaluation --trainout pendulum/01_train &
python3 plan-ddpg.py --evalout pendulum/02_evaluation --trainout pendulum/02_train &
python3 plan-ddpg.py --evalout pendulum/03_evaluation --trainout pendulum/03_train &
python3 plan-ddpg.py --evalout pendulum/04_evaluation --trainout pendulum/04_train &
python3 plan-ddpg.py --evalout pendulum/05_evaluation --trainout pendulum/05_train &
python3 plan-ddpg.py --evalout pendulum/06_evaluation --trainout pendulum/06_train &
python3 plan-ddpg.py --evalout pendulum/07_evaluation --trainout pendulum/07_train &
python3 plan-ddpg.py --evalout pendulum/08_evaluation --trainout pendulum/08_train &
python3 plan-ddpg.py --evalout pendulum/09_evaluation --trainout pendulum/09_train &
python3 plan-ddpg.py --evalout pendulum/10_evaluation --trainout pendulum/10_train &
